/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.collect.ContiguousSet;
import com.google.common.collect.Ordering;

import java.util.List;


/**
 * To start the application:
 * ./gradlew build
 * java -jar ./hw01-gradle/build/libs/gradleHelloWorld-0.1.jar
 * <p>
 * To unzip the jar:
 * unzip -l hw01-gradle.jar
 * unzip -l gradleHelloWorld-0.1.jar
 */
public class HelloOtus {
    public static void main(String... args) {
        int min = 0;
        int max = 100;
        List<Integer> example = ContiguousSet
                .closedOpen(min, max)
                .stream()
                .sorted(Ordering.natural().reversed())
                .toList();

        System.out.println(example);

    }
}
